# ---
# Build commands
# ---

[build]
  command = "yarn build"
  publish = "out"

# ---
# Functions
# ---

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@ampproject/toolbox-optimizer"]

# ---
# Plugins
# ---

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ---
# Redirects
# ---
# Page level and vanity redirects are housed in public/_redirects
# REMOVED MOST REDIRECTS

# Redirect blog feed requests to the headless admin domain
# this is needed to preserve the RSS feed
# using 200 to mask the request
[[redirects]]
  from = "/blog/feed"
  to = "/api/blog/feed"
  status = 200